name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Використовує останню версію

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Використовує останню версію
        with:
          node-version: '20'  # Оновлено до версії 20

      - name: Display Node.js version
        run: node -v  # Виводить версію Node.js

      - name: Display npm version
        run: npm -v  # Виводить версію npm

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

     
